### ISSUE TITLE
Is there any way to provide MSA of receptor for af2_metrics.py ?

### ISSUE THREAD

**Issue by jongseo-park** [RosettaCommons/RFDesign#12]
Hi, 

After design protein binder using hallucination.py, I tried to validate results.

According to the tutorials, first I run the trfold_relax.sh, 

and then run the af2_metrics.py .

However, the modeling result was implausible especially in the receptor region.

In the case of my receptor, the modeling result was plausible only if the MSA is provided.

I thought that the implausible result of af2_metrics.py might be originated from the modeling without MSA.

So, is there any protocol or alternative way to validate my result ?

Sincerely,
jongseo

**Comment by jueseph** [comment]
for binder-receptor complexes, you want to use af2_interface_metrics.py
rather than af2_metrics.py. however, in order to use this script you will
need to combine your pdbs into a silent file using silent_tools
<https://github.com/bcov77/silent_tools> (which requires an installation of
pyrosetta).

this script inputs a template for the receptor and puts an initial guess
for the binder, as described in this preprint
<https://www.biorxiv.org/content/10.1101/2022.06.15.495993v1>

**Comment by jongseo-park** [comment]
Cool ! Thanks
